FROM alpine:3.18

ENV HATHORIS_BIND=:8080
EXPOSE 8080
ENTRYPOINT ["/srv/hathoris"]
WORKDIR /var/lib/hathoris

RUN mkdir /var/lib/hathoris; apk --no-cache add alsa-utils pulseaudio-utils mpv yt-dlp

COPY hathoris /srv/hathoris
